name: Atlantis
favicon: null
layout_spectrum: 0.9441126564051956
typography_spectrum: 0.8698225407861173
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3381200486328453
  lightness: 0.7002724457997829
  saturation: 0.15734265698119998
  rhythmicContrast: 0.1480069679673761
purpose: []
